# sentiement analysis for maroccain languge

In [ ]:
import pandas as pd

In [ ]:
# df=pd.read_csv('train.csv')
df=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/M2(S3)/web mining/projet sentiement analysis for morcocain languge /sentiment-analysis-on-moroccan-arabic-dialect/train.csv')

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
df.head()

ID                                            comment  label
0   1  انا اوصي من هذا المنبر الكل للتوجه الى مراكز ا...      1
1   2  \nهناك الكثير لا يفهم المقصود كورونا ليست صعبة...      1
2   3  الحمد لله ارقام مقبولة مقارنة بدول المنطقة لول...      1
3   4  انا شخصيا أؤيد ما فرضته السلطات من ضرورة الإدل...      1
4   5  \nنفس الشئ في مدينة برشيد مراكز التلقيح مغلقة ...      1

In [ ]:
df.shape

(1920, 3)

In [ ]:
df.head()

ID                                            comment  label
0   1  انا اوصي من هذا المنبر الكل للتوجه الى مراكز ا...      1
1   2  \nهناك الكثير لا يفهم المقصود كورونا ليست صعبة...      1
2   3  الحمد لله ارقام مقبولة مقارنة بدول المنطقة لول...      1
3   4  انا شخصيا أؤيد ما فرضته السلطات من ضرورة الإدل...      1
4   5  \nنفس الشئ في مدينة برشيد مراكز التلقيح مغلقة ...      1

In [ ]:
df.isnull().sum()

ID         0
comment    0
label      0
dtype: int64

In [ ]:
###Drop Nan Values
df=df.dropna()


In [ ]:
df.head()

ID                                            comment  label
0   1  انا اوصي من هذا المنبر الكل للتوجه الى مراكز ا...      1
1   2  \nهناك الكثير لا يفهم المقصود كورونا ليست صعبة...      1
2   3  الحمد لله ارقام مقبولة مقارنة بدول المنطقة لول...      1
3   4  انا شخصيا أؤيد ما فرضته السلطات من ضرورة الإدل...      1
4   5  \nنفس الشئ في مدينة برشيد مراكز التلقيح مغلقة ...      1

In [ ]:
## Get the Independent Features

X=df.drop('label',axis=1)

In [ ]:
## Get the Dependent features
y=df['label']

In [ ]:
X.shape

(1920, 2)

In [ ]:
y.shape

(1920,)

In [ ]:
import tensorflow as tf

In [ ]:
tf.__version__

'2.14.0'

In [ ]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [ ]:
### Vocabulary size
voc_size=5000

### Onehot Representation

In [ ]:
messages=X.copy()

In [ ]:
messages['comment'][1]

'\nهناك الكثير لا يفهم المقصود كورونا ليست صعبة على الشباب لكنها صعبة على اصحاب مرض مزمن كالسكري …. لهذا الدولة اختارت ان تنقد امهاتنا و ابائنا و جميع مرضى السكري و من بعد ذلك قام قبل سيعم الجميع هو في الحقيقة عندما يتم التلقيح و يتم محاصرة الفيروس بالتلقيح ينتهي المشكل قبل أن يعم الفيروس كل الشرائح لهذا نتمنى ان تسرع الدولة في مخططها هذا لما له من تأثير على محاربة الوباء في اقرب وقت ممكن نتمنى من الله. التوفيق لكل من يساهم من بعيد او قريب على انجاح هذه المهمة و الشكر كذلك لصاحب الجلالة الذي لا يبخل في ان يكون هو السابق لمثل هذه المبادرة التي ستعود عليه بالصحة و العافية و تحية للشعب المغربي من طنجة إلى الݣرݣرات\n'

In [ ]:
messages

ID                                            comment
0        1  انا اوصي من هذا المنبر الكل للتوجه الى مراكز ا...
1        2  \nهناك الكثير لا يفهم المقصود كورونا ليست صعبة...
2        3  الحمد لله ارقام مقبولة مقارنة بدول المنطقة لول...
3        4  انا شخصيا أؤيد ما فرضته السلطات من ضرورة الإدل...
4        5  \nنفس الشئ في مدينة برشيد مراكز التلقيح مغلقة ...
...    ...                                                ...
1915  1916  \nوالله حتى دمرونا وتعداو علينا شي ميقراش\nشي ...
1916  1917                    لقاح موت و سم فيقو ا عباد الله 
1917  1918  اللقاح غير آمن، ولا يمكن تجاهل عشرات شهادات ال...
1918  1919  لنكن واقعيين…لا يجب فرظ التلقيح بالقوة..انا تل...
1919  1920  \n#التنسيقية_الوطنية_للمغاربة_الرافضين_للتلقيح...

[1920 rows x 2 columns]

In [ ]:
# import nltk
# import re
# from nltk.corpus import stopwords

In [ ]:
# nltk.download('stopwords')

In [ ]:
# ### Dataset Preprocessing
# from nltk.stem.porter import PorterStemmer ##stemming purpose
# ps = PorterStemmer()
# corpus = []
# for i in range(0, len(messages)):
#     review = re.sub('[^a-zA-Z]', ' ', messages['title'][i])
#     review = review.lower()
#     review = review.split()

#     review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
#     review = ' '.join(review)
#     corpus.append(review)

In [ ]:
import re

def pre_processing(df, field):
    lis=[]
    # Replace URLs, user mentions, and hashtags
    df[field] = df[field].replace(r'http\S+', 'URL', regex=True)
    df[field] = df[field].replace(r'www\S+', 'URL', regex=True)
    df[field] = df[field].replace(r'@[^\s]+', 'USER', regex=True)
    df[field] = df[field].replace(r'#[^\s]+', 'HASHTAG', regex=True)
    df = df[df[field].apply(lambda x: len(re.findall(r'[\u0600-\u06FF]+', x))) > 1]
    # df[field] = df[field].apply(strip_tatweel)
    # df[field] = df[field].apply(strip_tashkeel)

    symbols1 = re.compile('[/(){}\[\]\|,;]')
    symbols2 = re.compile("[@|(|)|\||:|>|<|_|#|\.|+|÷|×|'|!|\?|٪|؟\|&;*|[{|}]|\-|،|_’;!:^&%//]")
    arabic_punctuations = '''`÷×؛<>_()*&^%][ـ،/:"؟.,'{}~¦+|!”…“–ـ'''

    df[field] = df[field].apply(lambda x: re.sub(symbols1, ' ', x))
    df[field] = df[field].apply(lambda x: re.sub(symbols2, ' ', x))
    df[field] = df[field].apply(lambda x: re.sub('\n', ' ', x))
    # df[field]  =strip_tashkeel(df[field])
    # df[field]=strip_diacritics(df[field])
    # df[field]=normalize_ligature(df[field])
    for i in df['comment']:
      lis.append(i)


    return df

df = pre_processing(df, 'comment')


<ipython-input-101-5460b5844c15>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[field] = df[field].apply(lambda x: re.sub(symbols1, ' ', x))
<ipython-input-101-5460b5844c15>:19: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[field] = df[field].apply(lambda x: re.sub(symbols2, ' ', x))
<ipython-input-101-5460b5844c15>:20: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documenta

In [ ]:
y=df['label']
corpus=[comment  for comment in df['comment']]

In [ ]:
len(y)

1918

In [ ]:
corpus[1]

' هناك الكثير لا يفهم المقصود كورونا ليست صعبة على الشباب لكنها صعبة على اصحاب مرض مزمن كالسكري …  لهذا الدولة اختارت ان تنقد امهاتنا و ابائنا و جميع مرضى السكري و من بعد ذلك قام قبل سيعم الجميع هو في الحقيقة عندما يتم التلقيح و يتم محاصرة الفيروس بالتلقيح ينتهي المشكل قبل أن يعم الفيروس كل الشرائح لهذا نتمنى ان تسرع الدولة في مخططها هذا لما له من تأثير على محاربة الوباء في اقرب وقت ممكن نتمنى من الله  التوفيق لكل من يساهم من بعيد او قريب على انجاح هذه المهمة و الشكر كذلك لصاحب الجلالة الذي لا يبخل في ان يكون هو السابق لمثل هذه المبادرة التي ستعود عليه بالصحة و العافية و تحية للشعب المغربي من طنجة إلى الݣرݣرات '

In [ ]:
onehot_repr=[one_hot(words,voc_size)for words in corpus]
print(onehot_repr)

[[4137, 2861, 4982, 3050, 2271, 460, 3759, 1011, 328, 2365, 104, 4626, 4379, 4475, 73, 1049, 387, 939, 4213, 1049, 806, 4137, 3965, 438, 4982, 2397, 2653, 1319, 13, 2212, 2887, 1764, 4837, 2923, 2933, 3003, 682, 1806, 1011, 866, 203, 1939, 780, 4502, 3084, 1900, 4982, 4100, 4565, 190, 993, 1959, 4539, 3983, 3761, 689, 2226, 806, 3536, 3278, 720, 3050, 4550, 1682, 1805, 1177, 640, 108, 4544, 1693, 3501, 3620, 4982, 276, 1384, 3337, 4206, 1512, 3158, 2161, 3623, 3804, 4662, 4264, 3400, 3003], [1726, 90, 2653, 1852, 480, 4645, 3569, 3675, 2161, 4565, 1840, 3675, 2161, 1234, 1049, 1561, 1478, 1398, 3434, 3457, 139, 3337, 2867, 1963, 4940, 3632, 4940, 4927, 3539, 2502, 4940, 4982, 1069, 3866, 2702, 4876, 2457, 648, 939, 190, 3482, 2887, 4773, 2365, 4940, 4773, 1501, 2217, 3575, 2165, 4606, 4876, 2749, 4176, 2217, 3282, 1612, 3434, 1602, 3337, 3731, 3457, 190, 4555, 3050, 3490, 1419, 4982, 1035, 2161, 375, 4639, 190, 1588, 4036, 4677, 1602, 4982, 780, 584, 3645, 4982, 4639, 4982, 445, 73, 32

In [ ]:
corpus[1]

' هناك الكثير لا يفهم المقصود كورونا ليست صعبة على الشباب لكنها صعبة على اصحاب مرض مزمن كالسكري …  لهذا الدولة اختارت ان تنقد امهاتنا و ابائنا و جميع مرضى السكري و من بعد ذلك قام قبل سيعم الجميع هو في الحقيقة عندما يتم التلقيح و يتم محاصرة الفيروس بالتلقيح ينتهي المشكل قبل أن يعم الفيروس كل الشرائح لهذا نتمنى ان تسرع الدولة في مخططها هذا لما له من تأثير على محاربة الوباء في اقرب وقت ممكن نتمنى من الله  التوفيق لكل من يساهم من بعيد او قريب على انجاح هذه المهمة و الشكر كذلك لصاحب الجلالة الذي لا يبخل في ان يكون هو السابق لمثل هذه المبادرة التي ستعود عليه بالصحة و العافية و تحية للشعب المغربي من طنجة إلى الݣرݣرات '

### Embedding Representation

In [ ]:
sent_length=100
embedded_docs=pad_sequences(onehot_repr,padding='post',maxlen=sent_length)
print(embedded_docs)

[[4137 2861 4982 ...    0    0    0]
 [3337 2867 1963 ...  237 2090 3229]
 [4092 1557 4093 ...    0    0    0]
 ...
 [ 903  177 4940 ...    0    0    0]
 [  13 2226 4246 ...    0    0    0]
 [4880 3093  785 ...    0    0    0]]


In [ ]:
embedded_docs[1]

array([3337, 2867, 1963, 4940, 3632, 4940, 4927, 3539, 2502, 4940, 4982,
       1069, 3866, 2702, 4876, 2457,  648,  939,  190, 3482, 2887, 4773,
       2365, 4940, 4773, 1501, 2217, 3575, 2165, 4606, 4876, 2749, 4176,
       2217, 3282, 1612, 3434, 1602, 3337, 3731, 3457,  190, 4555, 3050,
       3490, 1419, 4982, 1035, 2161,  375, 4639,  190, 1588, 4036, 4677,
       1602, 4982,  780,  584, 3645, 4982, 4639, 4982,  445,   73, 3251,
       2161, 2040,   92,  702, 4940, 4537,  373, 2680, 4100, 3816, 2653,
        921,  190, 3337, 4821,  939, 2300, 3519,   92, 2458,  682, 1330,
         30, 4469, 4940,  504, 4940, 2852, 2438, 4147, 4982,  237, 2090,
       3229], dtype=int32)

In [ ]:
embedded_docs[0]

array([4137, 2861, 4982, 3050, 2271,  460, 3759, 1011,  328, 2365,  104,
       4626, 4379, 4475,   73, 1049,  387,  939, 4213, 1049,  806, 4137,
       3965,  438, 4982, 2397, 2653, 1319,   13, 2212, 2887, 1764, 4837,
       2923, 2933, 3003,  682, 1806, 1011,  866,  203, 1939,  780, 4502,
       3084, 1900, 4982, 4100, 4565,  190,  993, 1959, 4539, 3983, 3761,
        689, 2226,  806, 3536, 3278,  720, 3050, 4550, 1682, 1805, 1177,
        640,  108, 4544, 1693, 3501, 3620, 4982,  276, 1384, 3337, 4206,
       1512, 3158, 2161, 3623, 3804, 4662, 4264, 3400, 3003,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0], dtype=int32)

In [ ]:
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_3 (Embedding)     (None, 100, 40)           200000    
                                                                 
 lstm_3 (LSTM)               (None, 100)               56400     
                                                                 
 dense_3 (Dense)             (None, 1)                 101       
                                                                 
Total params: 256501 (1001.96 KB)
Trainable params: 256501 (1001.96 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [ ]:
len(embedded_docs),y.shape

(1918, (1918,))

In [ ]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [ ]:
X_final.shape,y_final.shape

((1918, 100), (1918,))

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

### Model Training

In [ ]:
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
21/21 [==============================] - 8s 271ms/step - loss: 0.6939 - accuracy: 0.5105 - val_loss: 0.6917 - val_accuracy: 0.5577
Epoch 2/10
21/21 [==============================] - 4s 196ms/step - loss: 0.6936 - accuracy: 0.5237 - val_loss: 0.6908 - val_accuracy: 0.5592
Epoch 3/10
21/21 [==============================] - 2s 115ms/step - loss: 0.6916 - accuracy: 0.5261 - val_loss: 0.6790 - val_accuracy: 0.5829
Epoch 4/10
21/21 [==============================] - 3s 142ms/step - loss: 0.6905 - accuracy: 0.5401 - val_loss: 0.6891 - val_accuracy: 0.5608
Epoch 5/10
21/21 [==============================] - 3s 127ms/step - loss: 0.6878 - accuracy: 0.5440 - val_loss: 0.6886 - val_accuracy: 0.5703
Epoch 6/10
21/21 [==============================] - 4s 190ms/step - loss: 0.6833 - accuracy: 0.5805 - val_loss: 0.6829 - val_accuracy: 0.5624
Epoch 7/10
21/21 [==============================] - 4s 180ms/step - loss: 0.6774 - accuracy: 0.5518 - val_loss: 0.6687 - val_accuracy: 0.5845
Epoch 

In [ ]:
from tensorflow.keras.layers import Dropout
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

### Performance










In [ ]:
y_pred=model.predict(X_test)

20/20 [==============================] - 1s 5ms/step


In [ ]:
y_pred=np.where(y_pred > 0.6, 1,0) ##AUC ROC Curve

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
confusion_matrix(y_test,y_pred)

array([[309,   0],
       [324,   0]])

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.4881516587677725

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.49      1.00      0.66       309
           1       0.00      0.00      0.00       324

    accuracy                           0.49       633
   macro avg       0.24      0.50      0.33       633
weighted avg       0.24      0.49      0.32       633



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
